/*
 * gpio.c
 *
 *  Created on: Jul 10, 2018
 *      Author: kidsr
 */

#include <pthread.h>
#include <wiringPi.h>

#include "gpio.h"

#define PINOPTION_GPIO		0x01
#define PINOPTION_I2C		0x02
#define PINOPTION_UART		0x04
#define PINOPTION_SPI		0x08
#define PINOPTION_HWPWM		0x10
#define PINOPTION_GPCLK		0x20
#define PINOPTION_PULLUP	0x40
#define PINOPTION_PULLDOWN	0x80

typedef struct {
	const GPIO_Pin_t	pin;
	bool				isSetup;
	const uint8_t		options;
	GPIO_PinConfig_t*	config;
} GPIO_PinSpec_t;

/* Pin specifications based on the Raspberry Pi standard */
static GPIO_PinSpec_t const *availablePins = {
	[GPIO_2_I2C1_SDA] 	= {0, false, PINOPTION_GPIO | PINOPTION_PULLUP | PINOPTION_I2C, NULL},
	[GPIO_3_I2C1_SCL] 	= {0, false, PINOPTION_GPIO | PINOPTION_PULLUP | PINOPTION_I2C, NULL},
	[GPIO_4_GPCLK0] 	= {0, false, PINOPTION_GPIO | PINOPTION_PULLUP | PINOPTION_GPCLK, NULL},
	[GPIO_5_GPCLK1] 	= {0, false, PINOPTION_GPIO | PINOPTION_PULLUP | PINOPTION_GPCLK, NULL},
	[GPIO_6_GPCLK2]		= {0, false, PINOPTION_GPIO | PINOPTION_PULLUP | PINOPTION_GPCLK, NULL},
	[GPIO_7_SPI0_CS1]	= {0, false, PINOPTION_GPIO | PINOPTION_PULLUP | PINOPTION_SPI, NULL},
	[GPIO_8_SPIO_CS0]	= {0, false, PINOPTION_GPIO | PINOPTION_PULLUP | PINOPTION_SPI, NULL},
	[GPIO_9_SPI0_MISO]	= {0, false, PINOPTION_GPIO | PINOPTION_PULLDOWN | PINOPTION_SPI, NULL},
	[GPIO_10_SPIO_MOSI]	= {0, false, PINOPTION_GPIO | PINOPTION_PULLDOWN | PINOPTION_SPI, NULL},
	[GPIO_11_SPI0_SCLK]	= {0, false, PINOPTION_GPIO | PINOPTION_PULLDOWN | PINOPTION_SPI, NULL},
	[GPIO_12]			= {0, false, PINOPTION_GPIO | PINOPTION_PULLDOWN, NULL},
	[GPIO_13]			= {0, false, PINOPTION_GPIO | PINOPTION_PULLDOWN, NULL},
	[GPIO_14_UART0_TXD]	= {0, true, PINOPTION_GPIO | PINOPTION_PULLDOWN | PINOPTION_UART, NULL},	// 'isSetup' true by default due to use by the OS as console
	[GPIO_15_UART0_RXD]	= {0, true, PINOPTION_GPIO | PINOPTION_PULLDOWN | PINOPTION_UART, NULL},	// 'isSetup' true by default due to use by the OS as console
	[GPIO_16_SPI1_CS0]	= {0, false, PINOPTION_GPIO | PINOPTION_PULLDOWN | PINOPTION_SPI, NULL},
	[GPIO_17]			= {0, false, PINOPTION_GPIO | PINOPTION_PULLDOWN, NULL},
	[GPIO_18_PWM]		= {0, false, PINOPTION_GPIO | PINOPTION_PULLDOWN | PINOPTION_HWPWM, NULL},
	[GPIO_19_SPI1_MISO]	= {0, false, PINOPTION_GPIO | PINOPTION_PULLDOWN | PINOPTION_SPI, NULL},
	[GPIO_20_SPI1_MOSI]	= {0, false, PINOPTION_GPIO | PINOPTION_PULLDOWN | PINOPTION_SPI, NULL},
	[GPIO_21_SPI1_SCLK]	= {0, false, PINOPTION_GPIO | PINOPTION_PULLDOWN | PINOPTION_SPI, NULL},
	[GPIO_22]			= {0, false, PINOPTION_GPIO | PINOPTION_PULLDOWN, NULL},
	[GPIO_23]			= {0, false, PINOPTION_GPIO | PINOPTION_PULLDOWN, NULL},
	[GPIO_24]			= {0, false, PINOPTION_GPIO | PINOPTION_PULLDOWN, NULL},
	[GPIO_25]			= {0, false, PINOPTION_GPIO | PINOPTION_PULLDOWN, NULL},
	[GPIO_26]			= {0, false, PINOPTION_GPIO | PINOPTION_PULLDOWN, NULL},
};

static pthread_t gpioListenerThread;


static void GPIO_input_listener(){

}
