# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: context.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='context.proto',
  package='piscan_pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rcontext.proto\x12\tpiscan_pb\"\xf6\x01\n\x05\x45ntry\x12\x0c\n\x04\x66req\x18\x01 \x01(\x04\x12\x11\n\tsystemTag\x18\x02 \x01(\t\x12\x10\n\x08\x65ntryTag\x18\x03 \x01(\t\x12\x12\n\nmodulation\x18\x04 \x01(\t\x12\x12\n\nentryIndex\x18\x05 \x01(\t\x12-\n\x0blockoutType\x18\x06 \x01(\x0e\x32\x18.piscan_pb.Entry.Lockout\x12\x17\n\x0flockoutDuration\x18\x07 \x01(\x05\x12\r\n\x05\x64\x65lay\x18\x08 \x01(\x05\";\n\x07Lockout\x12\x08\n\x04NONE\x10\x00\x12\t\n\x05TIMED\x10\x01\x12\x0b\n\x07SESSION\x10\x02\x12\x0e\n\nPERSISTENT\x10\x03\"\x1c\n\x0bSignalLevel\x12\r\n\x05level\x18\x01 \x01(\x05\"\xae\x01\n\x0eScannerContext\x12.\n\x05state\x18\x01 \x01(\x0e\x32\x1f.piscan_pb.ScannerContext.State\x12#\n\tentryData\x18\x02 \x01(\x0b\x32\x10.piscan_pb.Entry\x12\x12\n\nmanualHold\x18\x03 \x01(\x08\"3\n\x05State\x12\t\n\x05INVAL\x10\x00\x12\x08\n\x04SCAN\x10\x01\x12\x08\n\x04HOLD\x10\x02\x12\x0b\n\x07RECEIVE\x10\x03\"-\n\x0c\x44\x65modContext\x12\x0f\n\x07squelch\x18\x01 \x01(\x05\x12\x0c\n\x04gain\x18\x02 \x01(\x02\"\x86\x01\n\x0eGeneralMessage\x12,\n\x04type\x18\x01 \x01(\x0e\x32\x1e.piscan_pb.GeneralMessage.Type\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"5\n\x04Type\x12\x08\n\x04INFO\x10\x00\x12\x0b\n\x07WARNING\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x12\x0b\n\x07\x43ONSOLE\x10\x03\"|\n\nSystemInfo\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\r\n\x05\x62uild\x18\x02 \x01(\x05\x12\x17\n\x0fsquelchScaleMin\x18\x03 \x01(\x05\x12\x17\n\x0fsquelchScaleMax\x18\x04 \x01(\x05\x12\x1c\n\x14supportedModulations\x18\x05 \x03(\tb\x06proto3')
)



_ENTRY_LOCKOUT = _descriptor.EnumDescriptor(
  name='Lockout',
  full_name='piscan_pb.Entry.Lockout',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TIMED', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SESSION', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PERSISTENT', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=216,
  serialized_end=275,
)
_sym_db.RegisterEnumDescriptor(_ENTRY_LOCKOUT)

_SCANNERCONTEXT_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='piscan_pb.ScannerContext.State',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVAL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SCAN', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HOLD', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECEIVE', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=431,
  serialized_end=482,
)
_sym_db.RegisterEnumDescriptor(_SCANNERCONTEXT_STATE)

_GENERALMESSAGE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='piscan_pb.GeneralMessage.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INFO', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WARNING', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONSOLE', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=613,
  serialized_end=666,
)
_sym_db.RegisterEnumDescriptor(_GENERALMESSAGE_TYPE)


_ENTRY = _descriptor.Descriptor(
  name='Entry',
  full_name='piscan_pb.Entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='freq', full_name='piscan_pb.Entry.freq', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='systemTag', full_name='piscan_pb.Entry.systemTag', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entryTag', full_name='piscan_pb.Entry.entryTag', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='modulation', full_name='piscan_pb.Entry.modulation', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entryIndex', full_name='piscan_pb.Entry.entryIndex', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lockoutType', full_name='piscan_pb.Entry.lockoutType', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lockoutDuration', full_name='piscan_pb.Entry.lockoutDuration', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delay', full_name='piscan_pb.Entry.delay', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ENTRY_LOCKOUT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=275,
)


_SIGNALLEVEL = _descriptor.Descriptor(
  name='SignalLevel',
  full_name='piscan_pb.SignalLevel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='level', full_name='piscan_pb.SignalLevel.level', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=277,
  serialized_end=305,
)


_SCANNERCONTEXT = _descriptor.Descriptor(
  name='ScannerContext',
  full_name='piscan_pb.ScannerContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='piscan_pb.ScannerContext.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entryData', full_name='piscan_pb.ScannerContext.entryData', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='manualHold', full_name='piscan_pb.ScannerContext.manualHold', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SCANNERCONTEXT_STATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=308,
  serialized_end=482,
)


_DEMODCONTEXT = _descriptor.Descriptor(
  name='DemodContext',
  full_name='piscan_pb.DemodContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='squelch', full_name='piscan_pb.DemodContext.squelch', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gain', full_name='piscan_pb.DemodContext.gain', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=484,
  serialized_end=529,
)


_GENERALMESSAGE = _descriptor.Descriptor(
  name='GeneralMessage',
  full_name='piscan_pb.GeneralMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='piscan_pb.GeneralMessage.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='piscan_pb.GeneralMessage.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GENERALMESSAGE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=532,
  serialized_end=666,
)


_SYSTEMINFO = _descriptor.Descriptor(
  name='SystemInfo',
  full_name='piscan_pb.SystemInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='piscan_pb.SystemInfo.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='build', full_name='piscan_pb.SystemInfo.build', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='squelchScaleMin', full_name='piscan_pb.SystemInfo.squelchScaleMin', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='squelchScaleMax', full_name='piscan_pb.SystemInfo.squelchScaleMax', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='supportedModulations', full_name='piscan_pb.SystemInfo.supportedModulations', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=668,
  serialized_end=792,
)

_ENTRY.fields_by_name['lockoutType'].enum_type = _ENTRY_LOCKOUT
_ENTRY_LOCKOUT.containing_type = _ENTRY
_SCANNERCONTEXT.fields_by_name['state'].enum_type = _SCANNERCONTEXT_STATE
_SCANNERCONTEXT.fields_by_name['entryData'].message_type = _ENTRY
_SCANNERCONTEXT_STATE.containing_type = _SCANNERCONTEXT
_GENERALMESSAGE.fields_by_name['type'].enum_type = _GENERALMESSAGE_TYPE
_GENERALMESSAGE_TYPE.containing_type = _GENERALMESSAGE
DESCRIPTOR.message_types_by_name['Entry'] = _ENTRY
DESCRIPTOR.message_types_by_name['SignalLevel'] = _SIGNALLEVEL
DESCRIPTOR.message_types_by_name['ScannerContext'] = _SCANNERCONTEXT
DESCRIPTOR.message_types_by_name['DemodContext'] = _DEMODCONTEXT
DESCRIPTOR.message_types_by_name['GeneralMessage'] = _GENERALMESSAGE
DESCRIPTOR.message_types_by_name['SystemInfo'] = _SYSTEMINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Entry = _reflection.GeneratedProtocolMessageType('Entry', (_message.Message,), {
  'DESCRIPTOR' : _ENTRY,
  '__module__' : 'context_pb2'
  # @@protoc_insertion_point(class_scope:piscan_pb.Entry)
  })
_sym_db.RegisterMessage(Entry)

SignalLevel = _reflection.GeneratedProtocolMessageType('SignalLevel', (_message.Message,), {
  'DESCRIPTOR' : _SIGNALLEVEL,
  '__module__' : 'context_pb2'
  # @@protoc_insertion_point(class_scope:piscan_pb.SignalLevel)
  })
_sym_db.RegisterMessage(SignalLevel)

ScannerContext = _reflection.GeneratedProtocolMessageType('ScannerContext', (_message.Message,), {
  'DESCRIPTOR' : _SCANNERCONTEXT,
  '__module__' : 'context_pb2'
  # @@protoc_insertion_point(class_scope:piscan_pb.ScannerContext)
  })
_sym_db.RegisterMessage(ScannerContext)

DemodContext = _reflection.GeneratedProtocolMessageType('DemodContext', (_message.Message,), {
  'DESCRIPTOR' : _DEMODCONTEXT,
  '__module__' : 'context_pb2'
  # @@protoc_insertion_point(class_scope:piscan_pb.DemodContext)
  })
_sym_db.RegisterMessage(DemodContext)

GeneralMessage = _reflection.GeneratedProtocolMessageType('GeneralMessage', (_message.Message,), {
  'DESCRIPTOR' : _GENERALMESSAGE,
  '__module__' : 'context_pb2'
  # @@protoc_insertion_point(class_scope:piscan_pb.GeneralMessage)
  })
_sym_db.RegisterMessage(GeneralMessage)

SystemInfo = _reflection.GeneratedProtocolMessageType('SystemInfo', (_message.Message,), {
  'DESCRIPTOR' : _SYSTEMINFO,
  '__module__' : 'context_pb2'
  # @@protoc_insertion_point(class_scope:piscan_pb.SystemInfo)
  })
_sym_db.RegisterMessage(SystemInfo)


# @@protoc_insertion_point(module_scope)
