// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

#include "messages.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

extern PROTOBUF_INTERNAL_EXPORT_context_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_DemodContext_context_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_context_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_GeneralMessage_context_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_context_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SignalLevel_context_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_context_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SystemInfo_context_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_context_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_ScannerContext_context_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_request_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_DemodRequest_request_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_request_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_GeneralRequest_request_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_request_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_LockoutRequest_request_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_request_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ScannerStateRequest_request_2eproto;
namespace piscan_pb {
class ClientToServerDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ClientToServer> _instance;
  const ::piscan_pb::GeneralRequest* generalrequest_;
  const ::piscan_pb::ScannerStateRequest* scanstaterequest_;
  const ::piscan_pb::DemodRequest* demodrequest_;
  const ::piscan_pb::LockoutRequest* lockoutrequest_;
} _ClientToServer_default_instance_;
class ServerToClientDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ServerToClient> _instance;
  const ::piscan_pb::ScannerContext* scannercontext_;
  const ::piscan_pb::DemodContext* demodcontext_;
  const ::piscan_pb::GeneralMessage* generalmessage_;
  const ::piscan_pb::SystemInfo* systeminfo_;
  const ::piscan_pb::SignalLevel* signallevel_;
} _ServerToClient_default_instance_;
}  // namespace piscan_pb
static void InitDefaultsClientToServer_messages_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::piscan_pb::_ClientToServer_default_instance_;
    new (ptr) ::piscan_pb::ClientToServer();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::piscan_pb::ClientToServer::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<4> scc_info_ClientToServer_messages_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 4, InitDefaultsClientToServer_messages_2eproto}, {
      &scc_info_GeneralRequest_request_2eproto.base,
      &scc_info_ScannerStateRequest_request_2eproto.base,
      &scc_info_DemodRequest_request_2eproto.base,
      &scc_info_LockoutRequest_request_2eproto.base,}};

static void InitDefaultsServerToClient_messages_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::piscan_pb::_ServerToClient_default_instance_;
    new (ptr) ::piscan_pb::ServerToClient();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::piscan_pb::ServerToClient::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<5> scc_info_ServerToClient_messages_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 5, InitDefaultsServerToClient_messages_2eproto}, {
      &scc_info_ScannerContext_context_2eproto.base,
      &scc_info_DemodContext_context_2eproto.base,
      &scc_info_GeneralMessage_context_2eproto.base,
      &scc_info_SystemInfo_context_2eproto.base,
      &scc_info_SignalLevel_context_2eproto.base,}};

void InitDefaults_messages_2eproto() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ClientToServer_messages_2eproto.base);
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ServerToClient_messages_2eproto.base);
}

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_messages_2eproto[2];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_messages_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_messages_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_messages_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::piscan_pb::ClientToServer, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::piscan_pb::ClientToServer, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::piscan_pb::ClientToServer, type_),
  offsetof(::piscan_pb::ClientToServerDefaultTypeInternal, generalrequest_),
  offsetof(::piscan_pb::ClientToServerDefaultTypeInternal, scanstaterequest_),
  offsetof(::piscan_pb::ClientToServerDefaultTypeInternal, demodrequest_),
  offsetof(::piscan_pb::ClientToServerDefaultTypeInternal, lockoutrequest_),
  PROTOBUF_FIELD_OFFSET(::piscan_pb::ClientToServer, content_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::piscan_pb::ServerToClient, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::piscan_pb::ServerToClient, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::piscan_pb::ServerToClient, handle_),
  PROTOBUF_FIELD_OFFSET(::piscan_pb::ServerToClient, type_),
  offsetof(::piscan_pb::ServerToClientDefaultTypeInternal, scannercontext_),
  offsetof(::piscan_pb::ServerToClientDefaultTypeInternal, demodcontext_),
  offsetof(::piscan_pb::ServerToClientDefaultTypeInternal, generalmessage_),
  offsetof(::piscan_pb::ServerToClientDefaultTypeInternal, systeminfo_),
  offsetof(::piscan_pb::ServerToClientDefaultTypeInternal, signallevel_),
  PROTOBUF_FIELD_OFFSET(::piscan_pb::ServerToClient, content_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::piscan_pb::ClientToServer)},
  { 11, -1, sizeof(::piscan_pb::ServerToClient)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::piscan_pb::_ClientToServer_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::piscan_pb::_ServerToClient_default_instance_),
};

static ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptorsTable assign_descriptors_table_messages_2eproto = {
  {}, AddDescriptors_messages_2eproto, "messages.proto", schemas,
  file_default_instances, TableStruct_messages_2eproto::offsets,
  file_level_metadata_messages_2eproto, 2, file_level_enum_descriptors_messages_2eproto, file_level_service_descriptors_messages_2eproto,
};

const char descriptor_table_protodef_messages_2eproto[] =
  "\n\016messages.proto\022\tpiscan_pb\032\rrequest.pro"
  "to\032\rcontext.proto\"\200\003\n\016ClientToServer\022,\n\004"
  "type\030\001 \001(\0162\036.piscan_pb.ClientToServer.Ty"
  "pe\0223\n\016generalRequest\030\002 \001(\0132\031.piscan_pb.G"
  "eneralRequestH\000\022:\n\020scanStateRequest\030\003 \001("
  "\0132\036.piscan_pb.ScannerStateRequestH\000\022/\n\014d"
  "emodRequest\030\004 \001(\0132\027.piscan_pb.DemodReque"
  "stH\000\0223\n\016lockoutRequest\030\005 \001(\0132\031.piscan_pb"
  ".LockoutRequestH\000\"^\n\004Type\022\023\n\017GENERAL_REQ"
  "UEST\020\000\022\031\n\025SCANNER_STATE_REQUEST\020\001\022\021\n\rDEM"
  "OD_REQUEST\020\002\022\023\n\017LOCKOUT_REQUEST\020\003B\t\n\007con"
  "tent\"\275\003\n\016ServerToClient\022\016\n\006handle\030\001 \001(\005\022"
  ",\n\004type\030\002 \001(\0162\036.piscan_pb.ServerToClient"
  ".Type\0223\n\016scannerContext\030\003 \001(\0132\031.piscan_p"
  "b.ScannerContextH\000\022/\n\014demodContext\030\004 \001(\013"
  "2\027.piscan_pb.DemodContextH\000\0223\n\016generalMe"
  "ssage\030\005 \001(\0132\031.piscan_pb.GeneralMessageH\000"
  "\022+\n\nsystemInfo\030\006 \001(\0132\025.piscan_pb.SystemI"
  "nfoH\000\022-\n\013signalLevel\030\007 \001(\0132\026.piscan_pb.S"
  "ignalLevelH\000\"k\n\004Type\022\024\n\020REQUEST_RESPONSE"
  "\020\000\022\023\n\017SCANNER_CONTEXT\020\001\022\021\n\rDEMOD_CONTEXT"
  "\020\002\022\023\n\017GENERAL_MESSAGE\020\003\022\020\n\014SIGNAL_LEVEL\020"
  "\004B\t\n\007contentb\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_messages_2eproto = {
  false, InitDefaults_messages_2eproto, 
  descriptor_table_protodef_messages_2eproto,
  "messages.proto", &assign_descriptors_table_messages_2eproto, 900,
};

void AddDescriptors_messages_2eproto() {
  static constexpr ::PROTOBUF_NAMESPACE_ID::internal::InitFunc deps[2] =
  {
    ::AddDescriptors_request_2eproto,
    ::AddDescriptors_context_2eproto,
  };
 ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_messages_2eproto, deps, 2);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_messages_2eproto = []() { AddDescriptors_messages_2eproto(); return true; }();
namespace piscan_pb {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ClientToServer_Type_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&assign_descriptors_table_messages_2eproto);
  return file_level_enum_descriptors_messages_2eproto[0];
}
bool ClientToServer_Type_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr ClientToServer_Type ClientToServer::GENERAL_REQUEST;
constexpr ClientToServer_Type ClientToServer::SCANNER_STATE_REQUEST;
constexpr ClientToServer_Type ClientToServer::DEMOD_REQUEST;
constexpr ClientToServer_Type ClientToServer::LOCKOUT_REQUEST;
constexpr ClientToServer_Type ClientToServer::Type_MIN;
constexpr ClientToServer_Type ClientToServer::Type_MAX;
constexpr int ClientToServer::Type_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ServerToClient_Type_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&assign_descriptors_table_messages_2eproto);
  return file_level_enum_descriptors_messages_2eproto[1];
}
bool ServerToClient_Type_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr ServerToClient_Type ServerToClient::REQUEST_RESPONSE;
constexpr ServerToClient_Type ServerToClient::SCANNER_CONTEXT;
constexpr ServerToClient_Type ServerToClient::DEMOD_CONTEXT;
constexpr ServerToClient_Type ServerToClient::GENERAL_MESSAGE;
constexpr ServerToClient_Type ServerToClient::SIGNAL_LEVEL;
constexpr ServerToClient_Type ServerToClient::Type_MIN;
constexpr ServerToClient_Type ServerToClient::Type_MAX;
constexpr int ServerToClient::Type_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)

// ===================================================================

void ClientToServer::InitAsDefaultInstance() {
  ::piscan_pb::_ClientToServer_default_instance_.generalrequest_ = const_cast< ::piscan_pb::GeneralRequest*>(
      ::piscan_pb::GeneralRequest::internal_default_instance());
  ::piscan_pb::_ClientToServer_default_instance_.scanstaterequest_ = const_cast< ::piscan_pb::ScannerStateRequest*>(
      ::piscan_pb::ScannerStateRequest::internal_default_instance());
  ::piscan_pb::_ClientToServer_default_instance_.demodrequest_ = const_cast< ::piscan_pb::DemodRequest*>(
      ::piscan_pb::DemodRequest::internal_default_instance());
  ::piscan_pb::_ClientToServer_default_instance_.lockoutrequest_ = const_cast< ::piscan_pb::LockoutRequest*>(
      ::piscan_pb::LockoutRequest::internal_default_instance());
}
class ClientToServer::HasBitSetters {
 public:
  static const ::piscan_pb::GeneralRequest& generalrequest(const ClientToServer* msg);
  static const ::piscan_pb::ScannerStateRequest& scanstaterequest(const ClientToServer* msg);
  static const ::piscan_pb::DemodRequest& demodrequest(const ClientToServer* msg);
  static const ::piscan_pb::LockoutRequest& lockoutrequest(const ClientToServer* msg);
};

const ::piscan_pb::GeneralRequest&
ClientToServer::HasBitSetters::generalrequest(const ClientToServer* msg) {
  return *msg->content_.generalrequest_;
}
const ::piscan_pb::ScannerStateRequest&
ClientToServer::HasBitSetters::scanstaterequest(const ClientToServer* msg) {
  return *msg->content_.scanstaterequest_;
}
const ::piscan_pb::DemodRequest&
ClientToServer::HasBitSetters::demodrequest(const ClientToServer* msg) {
  return *msg->content_.demodrequest_;
}
const ::piscan_pb::LockoutRequest&
ClientToServer::HasBitSetters::lockoutrequest(const ClientToServer* msg) {
  return *msg->content_.lockoutrequest_;
}
void ClientToServer::set_allocated_generalrequest(::piscan_pb::GeneralRequest* generalrequest) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  clear_content();
  if (generalrequest) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      generalrequest = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, generalrequest, submessage_arena);
    }
    set_has_generalrequest();
    content_.generalrequest_ = generalrequest;
  }
  // @@protoc_insertion_point(field_set_allocated:piscan_pb.ClientToServer.generalRequest)
}
void ClientToServer::clear_generalrequest() {
  if (has_generalrequest()) {
    delete content_.generalrequest_;
    clear_has_content();
  }
}
void ClientToServer::set_allocated_scanstaterequest(::piscan_pb::ScannerStateRequest* scanstaterequest) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  clear_content();
  if (scanstaterequest) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      scanstaterequest = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, scanstaterequest, submessage_arena);
    }
    set_has_scanstaterequest();
    content_.scanstaterequest_ = scanstaterequest;
  }
  // @@protoc_insertion_point(field_set_allocated:piscan_pb.ClientToServer.scanStateRequest)
}
void ClientToServer::clear_scanstaterequest() {
  if (has_scanstaterequest()) {
    delete content_.scanstaterequest_;
    clear_has_content();
  }
}
void ClientToServer::set_allocated_demodrequest(::piscan_pb::DemodRequest* demodrequest) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  clear_content();
  if (demodrequest) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      demodrequest = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, demodrequest, submessage_arena);
    }
    set_has_demodrequest();
    content_.demodrequest_ = demodrequest;
  }
  // @@protoc_insertion_point(field_set_allocated:piscan_pb.ClientToServer.demodRequest)
}
void ClientToServer::clear_demodrequest() {
  if (has_demodrequest()) {
    delete content_.demodrequest_;
    clear_has_content();
  }
}
void ClientToServer::set_allocated_lockoutrequest(::piscan_pb::LockoutRequest* lockoutrequest) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  clear_content();
  if (lockoutrequest) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      lockoutrequest = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, lockoutrequest, submessage_arena);
    }
    set_has_lockoutrequest();
    content_.lockoutrequest_ = lockoutrequest;
  }
  // @@protoc_insertion_point(field_set_allocated:piscan_pb.ClientToServer.lockoutRequest)
}
void ClientToServer::clear_lockoutrequest() {
  if (has_lockoutrequest()) {
    delete content_.lockoutrequest_;
    clear_has_content();
  }
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ClientToServer::kTypeFieldNumber;
const int ClientToServer::kGeneralRequestFieldNumber;
const int ClientToServer::kScanStateRequestFieldNumber;
const int ClientToServer::kDemodRequestFieldNumber;
const int ClientToServer::kLockoutRequestFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ClientToServer::ClientToServer()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:piscan_pb.ClientToServer)
}
ClientToServer::ClientToServer(const ClientToServer& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  type_ = from.type_;
  clear_has_content();
  switch (from.content_case()) {
    case kGeneralRequest: {
      mutable_generalrequest()->::piscan_pb::GeneralRequest::MergeFrom(from.generalrequest());
      break;
    }
    case kScanStateRequest: {
      mutable_scanstaterequest()->::piscan_pb::ScannerStateRequest::MergeFrom(from.scanstaterequest());
      break;
    }
    case kDemodRequest: {
      mutable_demodrequest()->::piscan_pb::DemodRequest::MergeFrom(from.demodrequest());
      break;
    }
    case kLockoutRequest: {
      mutable_lockoutrequest()->::piscan_pb::LockoutRequest::MergeFrom(from.lockoutrequest());
      break;
    }
    case CONTENT_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:piscan_pb.ClientToServer)
}

void ClientToServer::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(
      &scc_info_ClientToServer_messages_2eproto.base);
  type_ = 0;
  clear_has_content();
}

ClientToServer::~ClientToServer() {
  // @@protoc_insertion_point(destructor:piscan_pb.ClientToServer)
  SharedDtor();
}

void ClientToServer::SharedDtor() {
  if (has_content()) {
    clear_content();
  }
}

void ClientToServer::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ClientToServer& ClientToServer::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ClientToServer_messages_2eproto.base);
  return *internal_default_instance();
}


void ClientToServer::clear_content() {
// @@protoc_insertion_point(one_of_clear_start:piscan_pb.ClientToServer)
  switch (content_case()) {
    case kGeneralRequest: {
      delete content_.generalrequest_;
      break;
    }
    case kScanStateRequest: {
      delete content_.scanstaterequest_;
      break;
    }
    case kDemodRequest: {
      delete content_.demodrequest_;
      break;
    }
    case kLockoutRequest: {
      delete content_.lockoutrequest_;
      break;
    }
    case CONTENT_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = CONTENT_NOT_SET;
}


void ClientToServer::Clear() {
// @@protoc_insertion_point(message_clear_start:piscan_pb.ClientToServer)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  type_ = 0;
  clear_content();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* ClientToServer::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // .piscan_pb.ClientToServer.Type type = 1;
      case 1: {
        if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) != 8) goto handle_unusual;
        ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        set_type(static_cast<::piscan_pb::ClientToServer_Type>(val));
        break;
      }
      // .piscan_pb.GeneralRequest generalRequest = 2;
      case 2: {
        if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) != 18) goto handle_unusual;
        ptr = ctx->ParseMessage(mutable_generalrequest(), ptr);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // .piscan_pb.ScannerStateRequest scanStateRequest = 3;
      case 3: {
        if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) != 26) goto handle_unusual;
        ptr = ctx->ParseMessage(mutable_scanstaterequest(), ptr);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // .piscan_pb.DemodRequest demodRequest = 4;
      case 4: {
        if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) != 34) goto handle_unusual;
        ptr = ctx->ParseMessage(mutable_demodrequest(), ptr);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // .piscan_pb.LockoutRequest lockoutRequest = 5;
      case 5: {
        if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) != 42) goto handle_unusual;
        ptr = ctx->ParseMessage(mutable_lockoutrequest(), ptr);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          return ptr;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        break;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool ClientToServer::MergePartialFromCodedStream(
    ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::PROTOBUF_NAMESPACE_ID::uint32 tag;
  // @@protoc_insertion_point(parse_start:piscan_pb.ClientToServer)
  for (;;) {
    ::std::pair<::PROTOBUF_NAMESPACE_ID::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .piscan_pb.ClientToServer.Type type = 1;
      case 1: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (8 & 0xFF)) {
          int value = 0;
          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   int, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::piscan_pb::ClientToServer_Type >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .piscan_pb.GeneralRequest generalRequest = 2;
      case 2: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (18 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_generalrequest()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .piscan_pb.ScannerStateRequest scanStateRequest = 3;
      case 3: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (26 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_scanstaterequest()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .piscan_pb.DemodRequest demodRequest = 4;
      case 4: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (34 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_demodrequest()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .piscan_pb.LockoutRequest lockoutRequest = 5;
      case 5: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (42 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_lockoutrequest()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:piscan_pb.ClientToServer)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:piscan_pb.ClientToServer)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void ClientToServer::SerializeWithCachedSizes(
    ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:piscan_pb.ClientToServer)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .piscan_pb.ClientToServer.Type type = 1;
  if (this->type() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  // .piscan_pb.GeneralRequest generalRequest = 2;
  if (has_generalrequest()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, HasBitSetters::generalrequest(this), output);
  }

  // .piscan_pb.ScannerStateRequest scanStateRequest = 3;
  if (has_scanstaterequest()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, HasBitSetters::scanstaterequest(this), output);
  }

  // .piscan_pb.DemodRequest demodRequest = 4;
  if (has_demodrequest()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, HasBitSetters::demodrequest(this), output);
  }

  // .piscan_pb.LockoutRequest lockoutRequest = 5;
  if (has_lockoutrequest()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, HasBitSetters::lockoutrequest(this), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:piscan_pb.ClientToServer)
}

::PROTOBUF_NAMESPACE_ID::uint8* ClientToServer::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:piscan_pb.ClientToServer)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .piscan_pb.ClientToServer.Type type = 1;
  if (this->type() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }

  // .piscan_pb.GeneralRequest generalRequest = 2;
  if (has_generalrequest()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, HasBitSetters::generalrequest(this), target);
  }

  // .piscan_pb.ScannerStateRequest scanStateRequest = 3;
  if (has_scanstaterequest()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, HasBitSetters::scanstaterequest(this), target);
  }

  // .piscan_pb.DemodRequest demodRequest = 4;
  if (has_demodrequest()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, HasBitSetters::demodrequest(this), target);
  }

  // .piscan_pb.LockoutRequest lockoutRequest = 5;
  if (has_lockoutrequest()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, HasBitSetters::lockoutrequest(this), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:piscan_pb.ClientToServer)
  return target;
}

size_t ClientToServer::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:piscan_pb.ClientToServer)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .piscan_pb.ClientToServer.Type type = 1;
  if (this->type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->type());
  }

  switch (content_case()) {
    // .piscan_pb.GeneralRequest generalRequest = 2;
    case kGeneralRequest: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *content_.generalrequest_);
      break;
    }
    // .piscan_pb.ScannerStateRequest scanStateRequest = 3;
    case kScanStateRequest: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *content_.scanstaterequest_);
      break;
    }
    // .piscan_pb.DemodRequest demodRequest = 4;
    case kDemodRequest: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *content_.demodrequest_);
      break;
    }
    // .piscan_pb.LockoutRequest lockoutRequest = 5;
    case kLockoutRequest: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *content_.lockoutrequest_);
      break;
    }
    case CONTENT_NOT_SET: {
      break;
    }
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ClientToServer::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:piscan_pb.ClientToServer)
  GOOGLE_DCHECK_NE(&from, this);
  const ClientToServer* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ClientToServer>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:piscan_pb.ClientToServer)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:piscan_pb.ClientToServer)
    MergeFrom(*source);
  }
}

void ClientToServer::MergeFrom(const ClientToServer& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:piscan_pb.ClientToServer)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.type() != 0) {
    set_type(from.type());
  }
  switch (from.content_case()) {
    case kGeneralRequest: {
      mutable_generalrequest()->::piscan_pb::GeneralRequest::MergeFrom(from.generalrequest());
      break;
    }
    case kScanStateRequest: {
      mutable_scanstaterequest()->::piscan_pb::ScannerStateRequest::MergeFrom(from.scanstaterequest());
      break;
    }
    case kDemodRequest: {
      mutable_demodrequest()->::piscan_pb::DemodRequest::MergeFrom(from.demodrequest());
      break;
    }
    case kLockoutRequest: {
      mutable_lockoutrequest()->::piscan_pb::LockoutRequest::MergeFrom(from.lockoutrequest());
      break;
    }
    case CONTENT_NOT_SET: {
      break;
    }
  }
}

void ClientToServer::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:piscan_pb.ClientToServer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ClientToServer::CopyFrom(const ClientToServer& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:piscan_pb.ClientToServer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClientToServer::IsInitialized() const {
  return true;
}

void ClientToServer::Swap(ClientToServer* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ClientToServer::InternalSwap(ClientToServer* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(type_, other->type_);
  swap(content_, other->content_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata ClientToServer::GetMetadata() const {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::assign_descriptors_table_messages_2eproto);
  return ::file_level_metadata_messages_2eproto[kIndexInFileMessages];
}


// ===================================================================

void ServerToClient::InitAsDefaultInstance() {
  ::piscan_pb::_ServerToClient_default_instance_.scannercontext_ = const_cast< ::piscan_pb::ScannerContext*>(
      ::piscan_pb::ScannerContext::internal_default_instance());
  ::piscan_pb::_ServerToClient_default_instance_.demodcontext_ = const_cast< ::piscan_pb::DemodContext*>(
      ::piscan_pb::DemodContext::internal_default_instance());
  ::piscan_pb::_ServerToClient_default_instance_.generalmessage_ = const_cast< ::piscan_pb::GeneralMessage*>(
      ::piscan_pb::GeneralMessage::internal_default_instance());
  ::piscan_pb::_ServerToClient_default_instance_.systeminfo_ = const_cast< ::piscan_pb::SystemInfo*>(
      ::piscan_pb::SystemInfo::internal_default_instance());
  ::piscan_pb::_ServerToClient_default_instance_.signallevel_ = const_cast< ::piscan_pb::SignalLevel*>(
      ::piscan_pb::SignalLevel::internal_default_instance());
}
class ServerToClient::HasBitSetters {
 public:
  static const ::piscan_pb::ScannerContext& scannercontext(const ServerToClient* msg);
  static const ::piscan_pb::DemodContext& demodcontext(const ServerToClient* msg);
  static const ::piscan_pb::GeneralMessage& generalmessage(const ServerToClient* msg);
  static const ::piscan_pb::SystemInfo& systeminfo(const ServerToClient* msg);
  static const ::piscan_pb::SignalLevel& signallevel(const ServerToClient* msg);
};

const ::piscan_pb::ScannerContext&
ServerToClient::HasBitSetters::scannercontext(const ServerToClient* msg) {
  return *msg->content_.scannercontext_;
}
const ::piscan_pb::DemodContext&
ServerToClient::HasBitSetters::demodcontext(const ServerToClient* msg) {
  return *msg->content_.demodcontext_;
}
const ::piscan_pb::GeneralMessage&
ServerToClient::HasBitSetters::generalmessage(const ServerToClient* msg) {
  return *msg->content_.generalmessage_;
}
const ::piscan_pb::SystemInfo&
ServerToClient::HasBitSetters::systeminfo(const ServerToClient* msg) {
  return *msg->content_.systeminfo_;
}
const ::piscan_pb::SignalLevel&
ServerToClient::HasBitSetters::signallevel(const ServerToClient* msg) {
  return *msg->content_.signallevel_;
}
void ServerToClient::set_allocated_scannercontext(::piscan_pb::ScannerContext* scannercontext) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  clear_content();
  if (scannercontext) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      scannercontext = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, scannercontext, submessage_arena);
    }
    set_has_scannercontext();
    content_.scannercontext_ = scannercontext;
  }
  // @@protoc_insertion_point(field_set_allocated:piscan_pb.ServerToClient.scannerContext)
}
void ServerToClient::clear_scannercontext() {
  if (has_scannercontext()) {
    delete content_.scannercontext_;
    clear_has_content();
  }
}
void ServerToClient::set_allocated_demodcontext(::piscan_pb::DemodContext* demodcontext) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  clear_content();
  if (demodcontext) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      demodcontext = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, demodcontext, submessage_arena);
    }
    set_has_demodcontext();
    content_.demodcontext_ = demodcontext;
  }
  // @@protoc_insertion_point(field_set_allocated:piscan_pb.ServerToClient.demodContext)
}
void ServerToClient::clear_demodcontext() {
  if (has_demodcontext()) {
    delete content_.demodcontext_;
    clear_has_content();
  }
}
void ServerToClient::set_allocated_generalmessage(::piscan_pb::GeneralMessage* generalmessage) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  clear_content();
  if (generalmessage) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      generalmessage = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, generalmessage, submessage_arena);
    }
    set_has_generalmessage();
    content_.generalmessage_ = generalmessage;
  }
  // @@protoc_insertion_point(field_set_allocated:piscan_pb.ServerToClient.generalMessage)
}
void ServerToClient::clear_generalmessage() {
  if (has_generalmessage()) {
    delete content_.generalmessage_;
    clear_has_content();
  }
}
void ServerToClient::set_allocated_systeminfo(::piscan_pb::SystemInfo* systeminfo) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  clear_content();
  if (systeminfo) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      systeminfo = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, systeminfo, submessage_arena);
    }
    set_has_systeminfo();
    content_.systeminfo_ = systeminfo;
  }
  // @@protoc_insertion_point(field_set_allocated:piscan_pb.ServerToClient.systemInfo)
}
void ServerToClient::clear_systeminfo() {
  if (has_systeminfo()) {
    delete content_.systeminfo_;
    clear_has_content();
  }
}
void ServerToClient::set_allocated_signallevel(::piscan_pb::SignalLevel* signallevel) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  clear_content();
  if (signallevel) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      signallevel = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, signallevel, submessage_arena);
    }
    set_has_signallevel();
    content_.signallevel_ = signallevel;
  }
  // @@protoc_insertion_point(field_set_allocated:piscan_pb.ServerToClient.signalLevel)
}
void ServerToClient::clear_signallevel() {
  if (has_signallevel()) {
    delete content_.signallevel_;
    clear_has_content();
  }
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ServerToClient::kHandleFieldNumber;
const int ServerToClient::kTypeFieldNumber;
const int ServerToClient::kScannerContextFieldNumber;
const int ServerToClient::kDemodContextFieldNumber;
const int ServerToClient::kGeneralMessageFieldNumber;
const int ServerToClient::kSystemInfoFieldNumber;
const int ServerToClient::kSignalLevelFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ServerToClient::ServerToClient()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:piscan_pb.ServerToClient)
}
ServerToClient::ServerToClient(const ServerToClient& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&handle_, &from.handle_,
    static_cast<size_t>(reinterpret_cast<char*>(&type_) -
    reinterpret_cast<char*>(&handle_)) + sizeof(type_));
  clear_has_content();
  switch (from.content_case()) {
    case kScannerContext: {
      mutable_scannercontext()->::piscan_pb::ScannerContext::MergeFrom(from.scannercontext());
      break;
    }
    case kDemodContext: {
      mutable_demodcontext()->::piscan_pb::DemodContext::MergeFrom(from.demodcontext());
      break;
    }
    case kGeneralMessage: {
      mutable_generalmessage()->::piscan_pb::GeneralMessage::MergeFrom(from.generalmessage());
      break;
    }
    case kSystemInfo: {
      mutable_systeminfo()->::piscan_pb::SystemInfo::MergeFrom(from.systeminfo());
      break;
    }
    case kSignalLevel: {
      mutable_signallevel()->::piscan_pb::SignalLevel::MergeFrom(from.signallevel());
      break;
    }
    case CONTENT_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:piscan_pb.ServerToClient)
}

void ServerToClient::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(
      &scc_info_ServerToClient_messages_2eproto.base);
  ::memset(&handle_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&type_) -
      reinterpret_cast<char*>(&handle_)) + sizeof(type_));
  clear_has_content();
}

ServerToClient::~ServerToClient() {
  // @@protoc_insertion_point(destructor:piscan_pb.ServerToClient)
  SharedDtor();
}

void ServerToClient::SharedDtor() {
  if (has_content()) {
    clear_content();
  }
}

void ServerToClient::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ServerToClient& ServerToClient::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ServerToClient_messages_2eproto.base);
  return *internal_default_instance();
}


void ServerToClient::clear_content() {
// @@protoc_insertion_point(one_of_clear_start:piscan_pb.ServerToClient)
  switch (content_case()) {
    case kScannerContext: {
      delete content_.scannercontext_;
      break;
    }
    case kDemodContext: {
      delete content_.demodcontext_;
      break;
    }
    case kGeneralMessage: {
      delete content_.generalmessage_;
      break;
    }
    case kSystemInfo: {
      delete content_.systeminfo_;
      break;
    }
    case kSignalLevel: {
      delete content_.signallevel_;
      break;
    }
    case CONTENT_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = CONTENT_NOT_SET;
}


void ServerToClient::Clear() {
// @@protoc_insertion_point(message_clear_start:piscan_pb.ServerToClient)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&handle_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&type_) -
      reinterpret_cast<char*>(&handle_)) + sizeof(type_));
  clear_content();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* ServerToClient::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // int32 handle = 1;
      case 1: {
        if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) != 8) goto handle_unusual;
        set_handle(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // .piscan_pb.ServerToClient.Type type = 2;
      case 2: {
        if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) != 16) goto handle_unusual;
        ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        set_type(static_cast<::piscan_pb::ServerToClient_Type>(val));
        break;
      }
      // .piscan_pb.ScannerContext scannerContext = 3;
      case 3: {
        if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) != 26) goto handle_unusual;
        ptr = ctx->ParseMessage(mutable_scannercontext(), ptr);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // .piscan_pb.DemodContext demodContext = 4;
      case 4: {
        if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) != 34) goto handle_unusual;
        ptr = ctx->ParseMessage(mutable_demodcontext(), ptr);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // .piscan_pb.GeneralMessage generalMessage = 5;
      case 5: {
        if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) != 42) goto handle_unusual;
        ptr = ctx->ParseMessage(mutable_generalmessage(), ptr);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // .piscan_pb.SystemInfo systemInfo = 6;
      case 6: {
        if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) != 50) goto handle_unusual;
        ptr = ctx->ParseMessage(mutable_systeminfo(), ptr);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // .piscan_pb.SignalLevel signalLevel = 7;
      case 7: {
        if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) != 58) goto handle_unusual;
        ptr = ctx->ParseMessage(mutable_signallevel(), ptr);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          return ptr;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        break;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool ServerToClient::MergePartialFromCodedStream(
    ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::PROTOBUF_NAMESPACE_ID::uint32 tag;
  // @@protoc_insertion_point(parse_start:piscan_pb.ServerToClient)
  for (;;) {
    ::std::pair<::PROTOBUF_NAMESPACE_ID::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 handle = 1;
      case 1: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (8 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32>(
                 input, &handle_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .piscan_pb.ServerToClient.Type type = 2;
      case 2: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (16 & 0xFF)) {
          int value = 0;
          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   int, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::piscan_pb::ServerToClient_Type >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .piscan_pb.ScannerContext scannerContext = 3;
      case 3: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (26 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_scannercontext()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .piscan_pb.DemodContext demodContext = 4;
      case 4: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (34 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_demodcontext()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .piscan_pb.GeneralMessage generalMessage = 5;
      case 5: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (42 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_generalmessage()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .piscan_pb.SystemInfo systemInfo = 6;
      case 6: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (50 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_systeminfo()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .piscan_pb.SignalLevel signalLevel = 7;
      case 7: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (58 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_signallevel()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:piscan_pb.ServerToClient)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:piscan_pb.ServerToClient)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void ServerToClient::SerializeWithCachedSizes(
    ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:piscan_pb.ServerToClient)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 handle = 1;
  if (this->handle() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32(1, this->handle(), output);
  }

  // .piscan_pb.ServerToClient.Type type = 2;
  if (this->type() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnum(
      2, this->type(), output);
  }

  // .piscan_pb.ScannerContext scannerContext = 3;
  if (has_scannercontext()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, HasBitSetters::scannercontext(this), output);
  }

  // .piscan_pb.DemodContext demodContext = 4;
  if (has_demodcontext()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, HasBitSetters::demodcontext(this), output);
  }

  // .piscan_pb.GeneralMessage generalMessage = 5;
  if (has_generalmessage()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, HasBitSetters::generalmessage(this), output);
  }

  // .piscan_pb.SystemInfo systemInfo = 6;
  if (has_systeminfo()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, HasBitSetters::systeminfo(this), output);
  }

  // .piscan_pb.SignalLevel signalLevel = 7;
  if (has_signallevel()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      7, HasBitSetters::signallevel(this), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:piscan_pb.ServerToClient)
}

::PROTOBUF_NAMESPACE_ID::uint8* ServerToClient::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:piscan_pb.ServerToClient)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 handle = 1;
  if (this->handle() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->handle(), target);
  }

  // .piscan_pb.ServerToClient.Type type = 2;
  if (this->type() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      2, this->type(), target);
  }

  // .piscan_pb.ScannerContext scannerContext = 3;
  if (has_scannercontext()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, HasBitSetters::scannercontext(this), target);
  }

  // .piscan_pb.DemodContext demodContext = 4;
  if (has_demodcontext()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, HasBitSetters::demodcontext(this), target);
  }

  // .piscan_pb.GeneralMessage generalMessage = 5;
  if (has_generalmessage()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, HasBitSetters::generalmessage(this), target);
  }

  // .piscan_pb.SystemInfo systemInfo = 6;
  if (has_systeminfo()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        6, HasBitSetters::systeminfo(this), target);
  }

  // .piscan_pb.SignalLevel signalLevel = 7;
  if (has_signallevel()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        7, HasBitSetters::signallevel(this), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:piscan_pb.ServerToClient)
  return target;
}

size_t ServerToClient::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:piscan_pb.ServerToClient)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 handle = 1;
  if (this->handle() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->handle());
  }

  // .piscan_pb.ServerToClient.Type type = 2;
  if (this->type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->type());
  }

  switch (content_case()) {
    // .piscan_pb.ScannerContext scannerContext = 3;
    case kScannerContext: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *content_.scannercontext_);
      break;
    }
    // .piscan_pb.DemodContext demodContext = 4;
    case kDemodContext: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *content_.demodcontext_);
      break;
    }
    // .piscan_pb.GeneralMessage generalMessage = 5;
    case kGeneralMessage: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *content_.generalmessage_);
      break;
    }
    // .piscan_pb.SystemInfo systemInfo = 6;
    case kSystemInfo: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *content_.systeminfo_);
      break;
    }
    // .piscan_pb.SignalLevel signalLevel = 7;
    case kSignalLevel: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *content_.signallevel_);
      break;
    }
    case CONTENT_NOT_SET: {
      break;
    }
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ServerToClient::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:piscan_pb.ServerToClient)
  GOOGLE_DCHECK_NE(&from, this);
  const ServerToClient* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ServerToClient>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:piscan_pb.ServerToClient)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:piscan_pb.ServerToClient)
    MergeFrom(*source);
  }
}

void ServerToClient::MergeFrom(const ServerToClient& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:piscan_pb.ServerToClient)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.handle() != 0) {
    set_handle(from.handle());
  }
  if (from.type() != 0) {
    set_type(from.type());
  }
  switch (from.content_case()) {
    case kScannerContext: {
      mutable_scannercontext()->::piscan_pb::ScannerContext::MergeFrom(from.scannercontext());
      break;
    }
    case kDemodContext: {
      mutable_demodcontext()->::piscan_pb::DemodContext::MergeFrom(from.demodcontext());
      break;
    }
    case kGeneralMessage: {
      mutable_generalmessage()->::piscan_pb::GeneralMessage::MergeFrom(from.generalmessage());
      break;
    }
    case kSystemInfo: {
      mutable_systeminfo()->::piscan_pb::SystemInfo::MergeFrom(from.systeminfo());
      break;
    }
    case kSignalLevel: {
      mutable_signallevel()->::piscan_pb::SignalLevel::MergeFrom(from.signallevel());
      break;
    }
    case CONTENT_NOT_SET: {
      break;
    }
  }
}

void ServerToClient::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:piscan_pb.ServerToClient)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ServerToClient::CopyFrom(const ServerToClient& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:piscan_pb.ServerToClient)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ServerToClient::IsInitialized() const {
  return true;
}

void ServerToClient::Swap(ServerToClient* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ServerToClient::InternalSwap(ServerToClient* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(handle_, other->handle_);
  swap(type_, other->type_);
  swap(content_, other->content_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata ServerToClient::GetMetadata() const {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::assign_descriptors_table_messages_2eproto);
  return ::file_level_metadata_messages_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace piscan_pb
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::piscan_pb::ClientToServer* Arena::CreateMaybeMessage< ::piscan_pb::ClientToServer >(Arena* arena) {
  return Arena::CreateInternal< ::piscan_pb::ClientToServer >(arena);
}
template<> PROTOBUF_NOINLINE ::piscan_pb::ServerToClient* Arena::CreateMaybeMessage< ::piscan_pb::ServerToClient >(Arena* arena) {
  return Arena::CreateInternal< ::piscan_pb::ServerToClient >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
