// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

#include "request.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace piscan_pb {
class GeneralRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<GeneralRequest> _instance;
} _GeneralRequest_default_instance_;
class ScannerStateRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ScannerStateRequest> _instance;
} _ScannerStateRequest_default_instance_;
class DemodRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<DemodRequest> _instance;
} _DemodRequest_default_instance_;
class LockoutRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<LockoutRequest> _instance;
} _LockoutRequest_default_instance_;
}  // namespace piscan_pb
static void InitDefaultsGeneralRequest_request_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::piscan_pb::_GeneralRequest_default_instance_;
    new (ptr) ::piscan_pb::GeneralRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::piscan_pb::GeneralRequest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_GeneralRequest_request_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsGeneralRequest_request_2eproto}, {}};

static void InitDefaultsScannerStateRequest_request_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::piscan_pb::_ScannerStateRequest_default_instance_;
    new (ptr) ::piscan_pb::ScannerStateRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::piscan_pb::ScannerStateRequest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ScannerStateRequest_request_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsScannerStateRequest_request_2eproto}, {}};

static void InitDefaultsDemodRequest_request_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::piscan_pb::_DemodRequest_default_instance_;
    new (ptr) ::piscan_pb::DemodRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::piscan_pb::DemodRequest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_DemodRequest_request_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsDemodRequest_request_2eproto}, {}};

static void InitDefaultsLockoutRequest_request_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::piscan_pb::_LockoutRequest_default_instance_;
    new (ptr) ::piscan_pb::LockoutRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::piscan_pb::LockoutRequest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_LockoutRequest_request_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsLockoutRequest_request_2eproto}, {}};

void InitDefaults_request_2eproto() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_GeneralRequest_request_2eproto.base);
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ScannerStateRequest_request_2eproto.base);
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_DemodRequest_request_2eproto.base);
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_LockoutRequest_request_2eproto.base);
}

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_request_2eproto[4];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_request_2eproto[4];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_request_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_request_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::piscan_pb::GeneralRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::piscan_pb::GeneralRequest, handle_),
  PROTOBUF_FIELD_OFFSET(::piscan_pb::GeneralRequest, type_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::piscan_pb::ScannerStateRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::piscan_pb::ScannerStateRequest, handle_),
  PROTOBUF_FIELD_OFFSET(::piscan_pb::ScannerStateRequest, state_),
  PROTOBUF_FIELD_OFFSET(::piscan_pb::ScannerStateRequest, manfreq_),
  PROTOBUF_FIELD_OFFSET(::piscan_pb::ScannerStateRequest, manmodulation_),
  PROTOBUF_FIELD_OFFSET(::piscan_pb::ScannerStateRequest, holdindex_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::piscan_pb::DemodRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::piscan_pb::DemodRequest, handle_),
  PROTOBUF_FIELD_OFFSET(::piscan_pb::DemodRequest, type_),
  PROTOBUF_FIELD_OFFSET(::piscan_pb::DemodRequest, level_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::piscan_pb::LockoutRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::piscan_pb::LockoutRequest, entryindex_),
  PROTOBUF_FIELD_OFFSET(::piscan_pb::LockoutRequest, lockouttype_),
  PROTOBUF_FIELD_OFFSET(::piscan_pb::LockoutRequest, lockoutduration_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::piscan_pb::GeneralRequest)},
  { 7, -1, sizeof(::piscan_pb::ScannerStateRequest)},
  { 17, -1, sizeof(::piscan_pb::DemodRequest)},
  { 25, -1, sizeof(::piscan_pb::LockoutRequest)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::piscan_pb::_GeneralRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::piscan_pb::_ScannerStateRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::piscan_pb::_DemodRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::piscan_pb::_LockoutRequest_default_instance_),
};

static ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptorsTable assign_descriptors_table_request_2eproto = {
  {}, AddDescriptors_request_2eproto, "request.proto", schemas,
  file_default_instances, TableStruct_request_2eproto::offsets,
  file_level_metadata_request_2eproto, 4, file_level_enum_descriptors_request_2eproto, file_level_service_descriptors_request_2eproto,
};

const char descriptor_table_protodef_request_2eproto[] =
  "\n\rrequest.proto\022\tpiscan_pb\"\235\001\n\016GeneralRe"
  "quest\022\016\n\006handle\030\001 \001(\005\0223\n\004type\030\002 \001(\0162%.pi"
  "scan_pb.GeneralRequest.RequestType\"F\n\013Re"
  "questType\022\023\n\017SCANNER_CONTEXT\020\000\022\021\n\rDEMOD_"
  "CONTEXT\020\001\022\017\n\013SYSTEM_INFO\020\002\"\304\001\n\023ScannerSt"
  "ateRequest\022\016\n\006handle\030\001 \001(\005\0226\n\005state\030\002 \001("
  "\0162\'.piscan_pb.ScannerStateRequest.NewSta"
  "te\022\017\n\007manFreq\030\003 \001(\003\022\025\n\rmanModulation\030\004 \001"
  "(\t\022\021\n\tholdIndex\030\005 \001(\t\"*\n\010NewState\022\010\n\004SCA"
  "N\020\000\022\010\n\004HOLD\020\001\022\n\n\006MANUAL\020\002\"\212\001\n\014DemodReque"
  "st\022\016\n\006handle\030\001 \001(\005\022/\n\004type\030\002 \001(\0162!.pisca"
  "n_pb.DemodRequest.DemodFunc\022\r\n\005level\030\003 \001"
  "(\002\"*\n\tDemodFunc\022\017\n\013SET_SQUELCH\020\000\022\014\n\010SET_"
  "GAIN\020\001\"\262\001\n\016LockoutRequest\022\022\n\nentryIndex\030"
  "\001 \001(\t\0226\n\013lockoutType\030\002 \001(\0162!.piscan_pb.L"
  "ockoutRequest.Lockout\022\027\n\017lockoutDuration"
  "\030\003 \001(\005\";\n\007Lockout\022\010\n\004NONE\020\000\022\t\n\005TIMED\020\001\022\013"
  "\n\007SESSION\020\002\022\016\n\nPERSISTENT\020\003b\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_request_2eproto = {
  false, InitDefaults_request_2eproto, 
  descriptor_table_protodef_request_2eproto,
  "request.proto", &assign_descriptors_table_request_2eproto, 715,
};

void AddDescriptors_request_2eproto() {
  static constexpr ::PROTOBUF_NAMESPACE_ID::internal::InitFunc deps[1] =
  {
  };
 ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_request_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_request_2eproto = []() { AddDescriptors_request_2eproto(); return true; }();
namespace piscan_pb {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* GeneralRequest_RequestType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&assign_descriptors_table_request_2eproto);
  return file_level_enum_descriptors_request_2eproto[0];
}
bool GeneralRequest_RequestType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr GeneralRequest_RequestType GeneralRequest::SCANNER_CONTEXT;
constexpr GeneralRequest_RequestType GeneralRequest::DEMOD_CONTEXT;
constexpr GeneralRequest_RequestType GeneralRequest::SYSTEM_INFO;
constexpr GeneralRequest_RequestType GeneralRequest::RequestType_MIN;
constexpr GeneralRequest_RequestType GeneralRequest::RequestType_MAX;
constexpr int GeneralRequest::RequestType_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ScannerStateRequest_NewState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&assign_descriptors_table_request_2eproto);
  return file_level_enum_descriptors_request_2eproto[1];
}
bool ScannerStateRequest_NewState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr ScannerStateRequest_NewState ScannerStateRequest::SCAN;
constexpr ScannerStateRequest_NewState ScannerStateRequest::HOLD;
constexpr ScannerStateRequest_NewState ScannerStateRequest::MANUAL;
constexpr ScannerStateRequest_NewState ScannerStateRequest::NewState_MIN;
constexpr ScannerStateRequest_NewState ScannerStateRequest::NewState_MAX;
constexpr int ScannerStateRequest::NewState_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DemodRequest_DemodFunc_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&assign_descriptors_table_request_2eproto);
  return file_level_enum_descriptors_request_2eproto[2];
}
bool DemodRequest_DemodFunc_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr DemodRequest_DemodFunc DemodRequest::SET_SQUELCH;
constexpr DemodRequest_DemodFunc DemodRequest::SET_GAIN;
constexpr DemodRequest_DemodFunc DemodRequest::DemodFunc_MIN;
constexpr DemodRequest_DemodFunc DemodRequest::DemodFunc_MAX;
constexpr int DemodRequest::DemodFunc_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* LockoutRequest_Lockout_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&assign_descriptors_table_request_2eproto);
  return file_level_enum_descriptors_request_2eproto[3];
}
bool LockoutRequest_Lockout_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr LockoutRequest_Lockout LockoutRequest::NONE;
constexpr LockoutRequest_Lockout LockoutRequest::TIMED;
constexpr LockoutRequest_Lockout LockoutRequest::SESSION;
constexpr LockoutRequest_Lockout LockoutRequest::PERSISTENT;
constexpr LockoutRequest_Lockout LockoutRequest::Lockout_MIN;
constexpr LockoutRequest_Lockout LockoutRequest::Lockout_MAX;
constexpr int LockoutRequest::Lockout_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)

// ===================================================================

void GeneralRequest::InitAsDefaultInstance() {
}
class GeneralRequest::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GeneralRequest::kHandleFieldNumber;
const int GeneralRequest::kTypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GeneralRequest::GeneralRequest()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:piscan_pb.GeneralRequest)
}
GeneralRequest::GeneralRequest(const GeneralRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&handle_, &from.handle_,
    static_cast<size_t>(reinterpret_cast<char*>(&type_) -
    reinterpret_cast<char*>(&handle_)) + sizeof(type_));
  // @@protoc_insertion_point(copy_constructor:piscan_pb.GeneralRequest)
}

void GeneralRequest::SharedCtor() {
  ::memset(&handle_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&type_) -
      reinterpret_cast<char*>(&handle_)) + sizeof(type_));
}

GeneralRequest::~GeneralRequest() {
  // @@protoc_insertion_point(destructor:piscan_pb.GeneralRequest)
  SharedDtor();
}

void GeneralRequest::SharedDtor() {
}

void GeneralRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GeneralRequest& GeneralRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_GeneralRequest_request_2eproto.base);
  return *internal_default_instance();
}


void GeneralRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:piscan_pb.GeneralRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&handle_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&type_) -
      reinterpret_cast<char*>(&handle_)) + sizeof(type_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* GeneralRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // int32 handle = 1;
      case 1: {
        if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) != 8) goto handle_unusual;
        set_handle(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // .piscan_pb.GeneralRequest.RequestType type = 2;
      case 2: {
        if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) != 16) goto handle_unusual;
        ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        set_type(static_cast<::piscan_pb::GeneralRequest_RequestType>(val));
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          return ptr;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        break;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool GeneralRequest::MergePartialFromCodedStream(
    ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::PROTOBUF_NAMESPACE_ID::uint32 tag;
  // @@protoc_insertion_point(parse_start:piscan_pb.GeneralRequest)
  for (;;) {
    ::std::pair<::PROTOBUF_NAMESPACE_ID::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 handle = 1;
      case 1: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (8 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32>(
                 input, &handle_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .piscan_pb.GeneralRequest.RequestType type = 2;
      case 2: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (16 & 0xFF)) {
          int value = 0;
          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   int, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::piscan_pb::GeneralRequest_RequestType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:piscan_pb.GeneralRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:piscan_pb.GeneralRequest)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void GeneralRequest::SerializeWithCachedSizes(
    ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:piscan_pb.GeneralRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 handle = 1;
  if (this->handle() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32(1, this->handle(), output);
  }

  // .piscan_pb.GeneralRequest.RequestType type = 2;
  if (this->type() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnum(
      2, this->type(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:piscan_pb.GeneralRequest)
}

::PROTOBUF_NAMESPACE_ID::uint8* GeneralRequest::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:piscan_pb.GeneralRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 handle = 1;
  if (this->handle() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->handle(), target);
  }

  // .piscan_pb.GeneralRequest.RequestType type = 2;
  if (this->type() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      2, this->type(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:piscan_pb.GeneralRequest)
  return target;
}

size_t GeneralRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:piscan_pb.GeneralRequest)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 handle = 1;
  if (this->handle() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->handle());
  }

  // .piscan_pb.GeneralRequest.RequestType type = 2;
  if (this->type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->type());
  }

  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GeneralRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:piscan_pb.GeneralRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const GeneralRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<GeneralRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:piscan_pb.GeneralRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:piscan_pb.GeneralRequest)
    MergeFrom(*source);
  }
}

void GeneralRequest::MergeFrom(const GeneralRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:piscan_pb.GeneralRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.handle() != 0) {
    set_handle(from.handle());
  }
  if (from.type() != 0) {
    set_type(from.type());
  }
}

void GeneralRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:piscan_pb.GeneralRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GeneralRequest::CopyFrom(const GeneralRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:piscan_pb.GeneralRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GeneralRequest::IsInitialized() const {
  return true;
}

void GeneralRequest::Swap(GeneralRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GeneralRequest::InternalSwap(GeneralRequest* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(handle_, other->handle_);
  swap(type_, other->type_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GeneralRequest::GetMetadata() const {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::assign_descriptors_table_request_2eproto);
  return ::file_level_metadata_request_2eproto[kIndexInFileMessages];
}


// ===================================================================

void ScannerStateRequest::InitAsDefaultInstance() {
}
class ScannerStateRequest::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ScannerStateRequest::kHandleFieldNumber;
const int ScannerStateRequest::kStateFieldNumber;
const int ScannerStateRequest::kManFreqFieldNumber;
const int ScannerStateRequest::kManModulationFieldNumber;
const int ScannerStateRequest::kHoldIndexFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ScannerStateRequest::ScannerStateRequest()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:piscan_pb.ScannerStateRequest)
}
ScannerStateRequest::ScannerStateRequest(const ScannerStateRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  manmodulation_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from.manmodulation().size() > 0) {
    manmodulation_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.manmodulation_);
  }
  holdindex_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from.holdindex().size() > 0) {
    holdindex_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.holdindex_);
  }
  ::memcpy(&handle_, &from.handle_,
    static_cast<size_t>(reinterpret_cast<char*>(&manfreq_) -
    reinterpret_cast<char*>(&handle_)) + sizeof(manfreq_));
  // @@protoc_insertion_point(copy_constructor:piscan_pb.ScannerStateRequest)
}

void ScannerStateRequest::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(
      &scc_info_ScannerStateRequest_request_2eproto.base);
  manmodulation_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  holdindex_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&handle_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&manfreq_) -
      reinterpret_cast<char*>(&handle_)) + sizeof(manfreq_));
}

ScannerStateRequest::~ScannerStateRequest() {
  // @@protoc_insertion_point(destructor:piscan_pb.ScannerStateRequest)
  SharedDtor();
}

void ScannerStateRequest::SharedDtor() {
  manmodulation_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  holdindex_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ScannerStateRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ScannerStateRequest& ScannerStateRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ScannerStateRequest_request_2eproto.base);
  return *internal_default_instance();
}


void ScannerStateRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:piscan_pb.ScannerStateRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  manmodulation_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  holdindex_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&handle_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&manfreq_) -
      reinterpret_cast<char*>(&handle_)) + sizeof(manfreq_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* ScannerStateRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // int32 handle = 1;
      case 1: {
        if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) != 8) goto handle_unusual;
        set_handle(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // .piscan_pb.ScannerStateRequest.NewState state = 2;
      case 2: {
        if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) != 16) goto handle_unusual;
        ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        set_state(static_cast<::piscan_pb::ScannerStateRequest_NewState>(val));
        break;
      }
      // int64 manFreq = 3;
      case 3: {
        if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) != 24) goto handle_unusual;
        set_manfreq(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // string manModulation = 4;
      case 4: {
        if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) != 34) goto handle_unusual;
        ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParserUTF8(mutable_manmodulation(), ptr, ctx, "piscan_pb.ScannerStateRequest.manModulation");
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // string holdIndex = 5;
      case 5: {
        if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) != 42) goto handle_unusual;
        ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParserUTF8(mutable_holdindex(), ptr, ctx, "piscan_pb.ScannerStateRequest.holdIndex");
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          return ptr;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        break;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool ScannerStateRequest::MergePartialFromCodedStream(
    ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::PROTOBUF_NAMESPACE_ID::uint32 tag;
  // @@protoc_insertion_point(parse_start:piscan_pb.ScannerStateRequest)
  for (;;) {
    ::std::pair<::PROTOBUF_NAMESPACE_ID::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 handle = 1;
      case 1: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (8 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32>(
                 input, &handle_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .piscan_pb.ScannerStateRequest.NewState state = 2;
      case 2: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (16 & 0xFF)) {
          int value = 0;
          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   int, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_state(static_cast< ::piscan_pb::ScannerStateRequest_NewState >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 manFreq = 3;
      case 3: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (24 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   ::PROTOBUF_NAMESPACE_ID::int64, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT64>(
                 input, &manfreq_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string manModulation = 4;
      case 4: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (34 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadString(
                input, this->mutable_manmodulation()));
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
            this->manmodulation().data(), static_cast<int>(this->manmodulation().length()),
            ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE,
            "piscan_pb.ScannerStateRequest.manModulation"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string holdIndex = 5;
      case 5: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (42 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadString(
                input, this->mutable_holdindex()));
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
            this->holdindex().data(), static_cast<int>(this->holdindex().length()),
            ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE,
            "piscan_pb.ScannerStateRequest.holdIndex"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:piscan_pb.ScannerStateRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:piscan_pb.ScannerStateRequest)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void ScannerStateRequest::SerializeWithCachedSizes(
    ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:piscan_pb.ScannerStateRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 handle = 1;
  if (this->handle() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32(1, this->handle(), output);
  }

  // .piscan_pb.ScannerStateRequest.NewState state = 2;
  if (this->state() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnum(
      2, this->state(), output);
  }

  // int64 manFreq = 3;
  if (this->manfreq() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64(3, this->manfreq(), output);
  }

  // string manModulation = 4;
  if (this->manmodulation().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->manmodulation().data(), static_cast<int>(this->manmodulation().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "piscan_pb.ScannerStateRequest.manModulation");
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->manmodulation(), output);
  }

  // string holdIndex = 5;
  if (this->holdindex().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->holdindex().data(), static_cast<int>(this->holdindex().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "piscan_pb.ScannerStateRequest.holdIndex");
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->holdindex(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:piscan_pb.ScannerStateRequest)
}

::PROTOBUF_NAMESPACE_ID::uint8* ScannerStateRequest::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:piscan_pb.ScannerStateRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 handle = 1;
  if (this->handle() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->handle(), target);
  }

  // .piscan_pb.ScannerStateRequest.NewState state = 2;
  if (this->state() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      2, this->state(), target);
  }

  // int64 manFreq = 3;
  if (this->manfreq() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(3, this->manfreq(), target);
  }

  // string manModulation = 4;
  if (this->manmodulation().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->manmodulation().data(), static_cast<int>(this->manmodulation().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "piscan_pb.ScannerStateRequest.manModulation");
    target =
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteStringToArray(
        4, this->manmodulation(), target);
  }

  // string holdIndex = 5;
  if (this->holdindex().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->holdindex().data(), static_cast<int>(this->holdindex().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "piscan_pb.ScannerStateRequest.holdIndex");
    target =
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteStringToArray(
        5, this->holdindex(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:piscan_pb.ScannerStateRequest)
  return target;
}

size_t ScannerStateRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:piscan_pb.ScannerStateRequest)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string manModulation = 4;
  if (this->manmodulation().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->manmodulation());
  }

  // string holdIndex = 5;
  if (this->holdindex().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->holdindex());
  }

  // int32 handle = 1;
  if (this->handle() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->handle());
  }

  // .piscan_pb.ScannerStateRequest.NewState state = 2;
  if (this->state() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->state());
  }

  // int64 manFreq = 3;
  if (this->manfreq() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->manfreq());
  }

  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ScannerStateRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:piscan_pb.ScannerStateRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const ScannerStateRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ScannerStateRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:piscan_pb.ScannerStateRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:piscan_pb.ScannerStateRequest)
    MergeFrom(*source);
  }
}

void ScannerStateRequest::MergeFrom(const ScannerStateRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:piscan_pb.ScannerStateRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.manmodulation().size() > 0) {

    manmodulation_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.manmodulation_);
  }
  if (from.holdindex().size() > 0) {

    holdindex_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.holdindex_);
  }
  if (from.handle() != 0) {
    set_handle(from.handle());
  }
  if (from.state() != 0) {
    set_state(from.state());
  }
  if (from.manfreq() != 0) {
    set_manfreq(from.manfreq());
  }
}

void ScannerStateRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:piscan_pb.ScannerStateRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ScannerStateRequest::CopyFrom(const ScannerStateRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:piscan_pb.ScannerStateRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ScannerStateRequest::IsInitialized() const {
  return true;
}

void ScannerStateRequest::Swap(ScannerStateRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ScannerStateRequest::InternalSwap(ScannerStateRequest* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  manmodulation_.Swap(&other->manmodulation_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  holdindex_.Swap(&other->holdindex_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(handle_, other->handle_);
  swap(state_, other->state_);
  swap(manfreq_, other->manfreq_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ScannerStateRequest::GetMetadata() const {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::assign_descriptors_table_request_2eproto);
  return ::file_level_metadata_request_2eproto[kIndexInFileMessages];
}


// ===================================================================

void DemodRequest::InitAsDefaultInstance() {
}
class DemodRequest::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DemodRequest::kHandleFieldNumber;
const int DemodRequest::kTypeFieldNumber;
const int DemodRequest::kLevelFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DemodRequest::DemodRequest()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:piscan_pb.DemodRequest)
}
DemodRequest::DemodRequest(const DemodRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&handle_, &from.handle_,
    static_cast<size_t>(reinterpret_cast<char*>(&level_) -
    reinterpret_cast<char*>(&handle_)) + sizeof(level_));
  // @@protoc_insertion_point(copy_constructor:piscan_pb.DemodRequest)
}

void DemodRequest::SharedCtor() {
  ::memset(&handle_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&level_) -
      reinterpret_cast<char*>(&handle_)) + sizeof(level_));
}

DemodRequest::~DemodRequest() {
  // @@protoc_insertion_point(destructor:piscan_pb.DemodRequest)
  SharedDtor();
}

void DemodRequest::SharedDtor() {
}

void DemodRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const DemodRequest& DemodRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_DemodRequest_request_2eproto.base);
  return *internal_default_instance();
}


void DemodRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:piscan_pb.DemodRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&handle_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&level_) -
      reinterpret_cast<char*>(&handle_)) + sizeof(level_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* DemodRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // int32 handle = 1;
      case 1: {
        if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) != 8) goto handle_unusual;
        set_handle(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // .piscan_pb.DemodRequest.DemodFunc type = 2;
      case 2: {
        if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) != 16) goto handle_unusual;
        ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        set_type(static_cast<::piscan_pb::DemodRequest_DemodFunc>(val));
        break;
      }
      // float level = 3;
      case 3: {
        if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) != 29) goto handle_unusual;
        set_level(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          return ptr;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        break;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool DemodRequest::MergePartialFromCodedStream(
    ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::PROTOBUF_NAMESPACE_ID::uint32 tag;
  // @@protoc_insertion_point(parse_start:piscan_pb.DemodRequest)
  for (;;) {
    ::std::pair<::PROTOBUF_NAMESPACE_ID::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 handle = 1;
      case 1: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (8 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32>(
                 input, &handle_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .piscan_pb.DemodRequest.DemodFunc type = 2;
      case 2: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (16 & 0xFF)) {
          int value = 0;
          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   int, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::piscan_pb::DemodRequest_DemodFunc >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float level = 3;
      case 3: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (29 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   float, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &level_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:piscan_pb.DemodRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:piscan_pb.DemodRequest)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void DemodRequest::SerializeWithCachedSizes(
    ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:piscan_pb.DemodRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 handle = 1;
  if (this->handle() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32(1, this->handle(), output);
  }

  // .piscan_pb.DemodRequest.DemodFunc type = 2;
  if (this->type() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnum(
      2, this->type(), output);
  }

  // float level = 3;
  if (this->level() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloat(3, this->level(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:piscan_pb.DemodRequest)
}

::PROTOBUF_NAMESPACE_ID::uint8* DemodRequest::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:piscan_pb.DemodRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 handle = 1;
  if (this->handle() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->handle(), target);
  }

  // .piscan_pb.DemodRequest.DemodFunc type = 2;
  if (this->type() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      2, this->type(), target);
  }

  // float level = 3;
  if (this->level() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(3, this->level(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:piscan_pb.DemodRequest)
  return target;
}

size_t DemodRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:piscan_pb.DemodRequest)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 handle = 1;
  if (this->handle() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->handle());
  }

  // .piscan_pb.DemodRequest.DemodFunc type = 2;
  if (this->type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->type());
  }

  // float level = 3;
  if (this->level() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DemodRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:piscan_pb.DemodRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const DemodRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<DemodRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:piscan_pb.DemodRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:piscan_pb.DemodRequest)
    MergeFrom(*source);
  }
}

void DemodRequest::MergeFrom(const DemodRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:piscan_pb.DemodRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.handle() != 0) {
    set_handle(from.handle());
  }
  if (from.type() != 0) {
    set_type(from.type());
  }
  if (from.level() != 0) {
    set_level(from.level());
  }
}

void DemodRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:piscan_pb.DemodRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DemodRequest::CopyFrom(const DemodRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:piscan_pb.DemodRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DemodRequest::IsInitialized() const {
  return true;
}

void DemodRequest::Swap(DemodRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DemodRequest::InternalSwap(DemodRequest* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(handle_, other->handle_);
  swap(type_, other->type_);
  swap(level_, other->level_);
}

::PROTOBUF_NAMESPACE_ID::Metadata DemodRequest::GetMetadata() const {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::assign_descriptors_table_request_2eproto);
  return ::file_level_metadata_request_2eproto[kIndexInFileMessages];
}


// ===================================================================

void LockoutRequest::InitAsDefaultInstance() {
}
class LockoutRequest::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LockoutRequest::kEntryIndexFieldNumber;
const int LockoutRequest::kLockoutTypeFieldNumber;
const int LockoutRequest::kLockoutDurationFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LockoutRequest::LockoutRequest()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:piscan_pb.LockoutRequest)
}
LockoutRequest::LockoutRequest(const LockoutRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  entryindex_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from.entryindex().size() > 0) {
    entryindex_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.entryindex_);
  }
  ::memcpy(&lockouttype_, &from.lockouttype_,
    static_cast<size_t>(reinterpret_cast<char*>(&lockoutduration_) -
    reinterpret_cast<char*>(&lockouttype_)) + sizeof(lockoutduration_));
  // @@protoc_insertion_point(copy_constructor:piscan_pb.LockoutRequest)
}

void LockoutRequest::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(
      &scc_info_LockoutRequest_request_2eproto.base);
  entryindex_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&lockouttype_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&lockoutduration_) -
      reinterpret_cast<char*>(&lockouttype_)) + sizeof(lockoutduration_));
}

LockoutRequest::~LockoutRequest() {
  // @@protoc_insertion_point(destructor:piscan_pb.LockoutRequest)
  SharedDtor();
}

void LockoutRequest::SharedDtor() {
  entryindex_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void LockoutRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const LockoutRequest& LockoutRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_LockoutRequest_request_2eproto.base);
  return *internal_default_instance();
}


void LockoutRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:piscan_pb.LockoutRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  entryindex_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&lockouttype_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&lockoutduration_) -
      reinterpret_cast<char*>(&lockouttype_)) + sizeof(lockoutduration_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* LockoutRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // string entryIndex = 1;
      case 1: {
        if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParserUTF8(mutable_entryindex(), ptr, ctx, "piscan_pb.LockoutRequest.entryIndex");
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // .piscan_pb.LockoutRequest.Lockout lockoutType = 2;
      case 2: {
        if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) != 16) goto handle_unusual;
        ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        set_lockouttype(static_cast<::piscan_pb::LockoutRequest_Lockout>(val));
        break;
      }
      // int32 lockoutDuration = 3;
      case 3: {
        if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) != 24) goto handle_unusual;
        set_lockoutduration(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          return ptr;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        break;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool LockoutRequest::MergePartialFromCodedStream(
    ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::PROTOBUF_NAMESPACE_ID::uint32 tag;
  // @@protoc_insertion_point(parse_start:piscan_pb.LockoutRequest)
  for (;;) {
    ::std::pair<::PROTOBUF_NAMESPACE_ID::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string entryIndex = 1;
      case 1: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (10 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadString(
                input, this->mutable_entryindex()));
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
            this->entryindex().data(), static_cast<int>(this->entryindex().length()),
            ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE,
            "piscan_pb.LockoutRequest.entryIndex"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .piscan_pb.LockoutRequest.Lockout lockoutType = 2;
      case 2: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (16 & 0xFF)) {
          int value = 0;
          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   int, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_lockouttype(static_cast< ::piscan_pb::LockoutRequest_Lockout >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 lockoutDuration = 3;
      case 3: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (24 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32>(
                 input, &lockoutduration_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:piscan_pb.LockoutRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:piscan_pb.LockoutRequest)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void LockoutRequest::SerializeWithCachedSizes(
    ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:piscan_pb.LockoutRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string entryIndex = 1;
  if (this->entryindex().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->entryindex().data(), static_cast<int>(this->entryindex().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "piscan_pb.LockoutRequest.entryIndex");
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->entryindex(), output);
  }

  // .piscan_pb.LockoutRequest.Lockout lockoutType = 2;
  if (this->lockouttype() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnum(
      2, this->lockouttype(), output);
  }

  // int32 lockoutDuration = 3;
  if (this->lockoutduration() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32(3, this->lockoutduration(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:piscan_pb.LockoutRequest)
}

::PROTOBUF_NAMESPACE_ID::uint8* LockoutRequest::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:piscan_pb.LockoutRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string entryIndex = 1;
  if (this->entryindex().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->entryindex().data(), static_cast<int>(this->entryindex().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "piscan_pb.LockoutRequest.entryIndex");
    target =
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteStringToArray(
        1, this->entryindex(), target);
  }

  // .piscan_pb.LockoutRequest.Lockout lockoutType = 2;
  if (this->lockouttype() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      2, this->lockouttype(), target);
  }

  // int32 lockoutDuration = 3;
  if (this->lockoutduration() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->lockoutduration(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:piscan_pb.LockoutRequest)
  return target;
}

size_t LockoutRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:piscan_pb.LockoutRequest)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string entryIndex = 1;
  if (this->entryindex().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->entryindex());
  }

  // .piscan_pb.LockoutRequest.Lockout lockoutType = 2;
  if (this->lockouttype() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->lockouttype());
  }

  // int32 lockoutDuration = 3;
  if (this->lockoutduration() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->lockoutduration());
  }

  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void LockoutRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:piscan_pb.LockoutRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const LockoutRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<LockoutRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:piscan_pb.LockoutRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:piscan_pb.LockoutRequest)
    MergeFrom(*source);
  }
}

void LockoutRequest::MergeFrom(const LockoutRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:piscan_pb.LockoutRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.entryindex().size() > 0) {

    entryindex_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.entryindex_);
  }
  if (from.lockouttype() != 0) {
    set_lockouttype(from.lockouttype());
  }
  if (from.lockoutduration() != 0) {
    set_lockoutduration(from.lockoutduration());
  }
}

void LockoutRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:piscan_pb.LockoutRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LockoutRequest::CopyFrom(const LockoutRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:piscan_pb.LockoutRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LockoutRequest::IsInitialized() const {
  return true;
}

void LockoutRequest::Swap(LockoutRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LockoutRequest::InternalSwap(LockoutRequest* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  entryindex_.Swap(&other->entryindex_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(lockouttype_, other->lockouttype_);
  swap(lockoutduration_, other->lockoutduration_);
}

::PROTOBUF_NAMESPACE_ID::Metadata LockoutRequest::GetMetadata() const {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::assign_descriptors_table_request_2eproto);
  return ::file_level_metadata_request_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace piscan_pb
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::piscan_pb::GeneralRequest* Arena::CreateMaybeMessage< ::piscan_pb::GeneralRequest >(Arena* arena) {
  return Arena::CreateInternal< ::piscan_pb::GeneralRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::piscan_pb::ScannerStateRequest* Arena::CreateMaybeMessage< ::piscan_pb::ScannerStateRequest >(Arena* arena) {
  return Arena::CreateInternal< ::piscan_pb::ScannerStateRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::piscan_pb::DemodRequest* Arena::CreateMaybeMessage< ::piscan_pb::DemodRequest >(Arena* arena) {
  return Arena::CreateInternal< ::piscan_pb::DemodRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::piscan_pb::LockoutRequest* Arena::CreateMaybeMessage< ::piscan_pb::LockoutRequest >(Arena* arena) {
  return Arena::CreateInternal< ::piscan_pb::LockoutRequest >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
